### ISSUE TITLE
お気に入りボタンの処遇を決める

### ISSUE THREAD

**Issue by mugiply** [rairus00/otokara-imas#2]
当初、「カラオケ楽曲をお気に入り登録して、リスト表示する」といった使い方を実現するために、楽曲カードに「お気に入り」ボタンを用意しました。
しかし、あまり必要性がなかったということで、中身を実装せずにおいてあります。

「お気に入り」ボタンの今後の処遇を決める必要があります。

**Comment by rairus00** [comment]
前提として、楽曲のお気に入り登録はDAM公式アプリ(デンモクアプリ)側で実現可能なため、機能の中身が未実装となっています。
しかし、デンモクアプリのお気に入り登録には「DAM★とも」へのログインが必要なため、会員登録など若干ハードルが高く感じられます。

以上の理由から、優先度低ではありますが「楽曲のお気に入り登録(マイリスト機能？)の実装」を行いたいと思います。

**Comment by rairus00** [comment]
方針決定したのでクローズします
